version: '3'
services:
  nginx:
    image: victorhad/vwapp:nginx
    container_name: vwapp-nginx
    build: .
    ports:
      - "443:8000"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/usr/share/nginx/html
      - ./.ignore/logs:/var/log/nginx