version: '3'
services:
  nginx:
    image: vwapplication/vwapp:nginx
    container_name: vwapp-nginx
    build: .
    ports:
      - "443:8000"
      - "80:80"
    volumes:
      - ./.ignore/nginx:/var/log/nginx